About Us page
Shavit-Lab/website pull request #5
Opened 2024-09-11 20:57 UTC by pythonLoader

The about page would contain the current members and alumni information.

2024-09-12 12:44 UTC, tathey1 requested changes
Looks good but I have two comments:
- I think you accidentally added two photos of Ling (can you remove Linghao.jpg?)
- I propose that in the future, new members are responsible for adding themselves to the website. Can you add a brief blurb to the README with instructions on how someone would add themselves to this page?

2024-09-13 13:04 UTC, pythonLoader commented
Fixed the image issue, and added a small blurb on the README. Can you merge this if everything looks good?

2024-09-13 13:52 UTC, Lin-K76 approved these changes
Looks good to me!

2024-09-13 18:04 UTC, tathey1 approved these changes

2024-09-13 18:04 UTC, merged